---
- name: "Create ELK stack root directory if it does not exist"
  become: yes
  become_user: root
  ansible.builtin.file:
    path: "{{ ES_HOME }}"
    state: directory
    group: ubuntu
    owner: ubuntu
    mode: '0755'

- name: Delete Previous installation
  file:
    path: "{{ DEPLOYMENT_HOME }}"
    state: absent

- name: "Create {{ DEPLOYMENT }} directory if it does not exist"
  become: yes
  become_user: ubuntu
  ansible.builtin.file:
    path: "{{ DEPLOYMENT_HOME }}"
    state: directory
    mode: '0755'

- name: "Create {{ DEPLOYMENT }} log directory if it does not exist"
  become: yes
  become_user: root
  ansible.builtin.file:
    path: "/var/log/{{ DEPLOYMENT }}"
    state: directory
    group: ubuntu
    owner: ubuntu
    mode: '0755'

- name: Download {{ DEPLOYMENT }} installation archive
  become: yes
  become_user: ubuntu
  get_url:
    url: "{{ DEPLOYMENT_ARTIFACT }}"
    dest: "{{ DEPLOYMENT_HOME }}/{{DEPLOYMENT}}.tar.gz"
    validate_certs: no
    force: yes

- name: Unarchive {{ DEPLOYMENT }} installation archive
  become: yes
  become_user: ubuntu
  unarchive:
    src: "{{ DEPLOYMENT_HOME }}/{{DEPLOYMENT}}.tar.gz"
    dest: "{{ DEPLOYMENT_HOME }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Remove {{ DEPLOYMENT }} installation archive
  become: yes
  become_user: ubuntu
  ansible.builtin.file:
    path: "{{ DEPLOYMENT_HOME }}/{{DEPLOYMENT}}.tar.gz"
    state: absent

- name: Create {{DEPLOYMENT}} Keystore
  become: yes
  become_user: ubuntu
  ansible.builtin.expect:
    command: "{{ DEPLOYMENT_HOME }}/bin/{{DEPLOYMENT}}-keystore create"
    responses:
      '[y/N]': y
    
- name: Add Elasticsearch username to Keystore
  become: yes
  become_user: ubuntu
  command: "{{ DEPLOYMENT_HOME }}/bin/{{DEPLOYMENT}}-keystore add 'elasticsearch.username' --stdin"
  args:
    stdin: elastic

- name: Add Elasticsearch Password to Keystore
  become: yes
  become_user: ubuntu
  command: "{{ DEPLOYMENT_HOME }}/bin/{{DEPLOYMENT}}-keystore add 'elasticsearch.password' --stdin"
  args:
    stdin: "{{ES_PWD}}"

- name: Copy custom {{DEPLOYMENT}} log4j
  become: yes
  become_user: ubuntu
  ansible.builtin.template:
    src: files/log4j2.properties
    dest: "{{ DEPLOYMENT_HOME }}/config/log4j2.properties"
    mode: '0644'

- name: Copy custom {{DEPLOYMENT}} yml
  become: yes
  become_user: ubuntu
  ansible.builtin.template:
    src: files/{{DEPLOYMENT}}.yml
    dest: "{{ DEPLOYMENT_HOME }}/config/{{ DEPLOYMENT}}.yml"
    mode: '0644'

- name: Copy custom {{DEPLOYMENT}} pipeline yml
  become: yes
  become_user: ubuntu
  ansible.builtin.template:
    src: files/pipelines.yml
    dest: "{{ DEPLOYMENT_HOME }}/config/pipelines.yml"
    mode: '0644'


- name: Copy pipelines config for {{DEPLOYMENT}}
  become: yes
  become_user: ubuntu
  ansible.builtin.copy:
    src: files/conf.d
    dest: "{{ DEPLOYMENT_HOME }}"
    mode: '0755'


- name: Copy start script for {{DEPLOYMENT}}
  become: yes
  become_user: ubuntu
  ansible.builtin.template:
    src: files/start.sh
    dest: "{{ DEPLOYMENT_HOME }}/start.sh"
    mode: '0755'


- name: Copy CA File 
  become: yes
  become_user: ubuntu
  ansible.builtin.template:
    src: files/ca.crt
    dest: "{{ DEPLOYMENT_HOME }}/config/ca.crt"
    mode: '0750'



- name: Start {{DEPLOYMENT}}
  become: yes
  become_user: ubuntu
  shell: nohup {{ DEPLOYMENT_HOME }}/start.sh
 