path:
    data: /home/ubuntu/elasticsearch/data
    logs: /var/log/elasticsearch


cluster.name: poc-cluster

node.name: poc-node
network.host: 0.0.0.0

cluster.initial_master_nodes: poc-node




xpack:
  security:
    enabled: true
    transport.ssl:
      enabled: true
      key: es01.key
      certificate: es01.crt
      certificate_authorities: ca.crt
      verification_mode: certificate
    http.ssl:
      enabled: true
      key: es01.key
      certificate: es01.crt
      certificate_authorities: ca.crt
      verification_mode: certificate
