path:
    data: /home/ubuntu/elasticsearch/data
    logs: /var/log/elasticsearch


cluster.name: elastic-cluster

node.name: main-node
network.host: 0.0.0.0

cluster.initial_master_nodes: main-node




xpack:
  security:
    enabled: true
    transport.ssl:
      enabled: true
      key: elastic.key
      certificate: elastic.crt
      certificate_authorities: ca.crt
      verification_mode: certificate
    http.ssl:
      enabled: true
      key: elastic.key
      certificate: elastic.crt
      certificate_authorities: ca.crt
      verification_mode: certificate
