---
path.data: "{{DEPLOYMENT_HOME}}/config"
server.host: "0.0.0.0"

elasticsearch.hosts:
  - "https://localhost:9200"

elasticsearch.ssl:
  certificateAuthorities: "{{DEPLOYMENT_HOME}}/config/ca.crt"
  verificationMode: certificate


server.ssl:
  enabled: true
  certificate: "{{DEPLOYMENT_HOME}}/config/kibana.crt"
  key: "{{DEPLOYMENT_HOME}}/config/kibana.key"
  certificateAuthorities: "{{DEPLOYMENT_HOME}}/config/ca.crt"