---
path.data: "{{DEPLOYMENT_HOME}}/config"
elasticsearch.hosts:
  - "https://localhost:9200"

elasticsearch.ssl.verificationMode: none
# elasticsearch.username: "elastic"
# elasticsearch.password: "${ES_PWD}" 

server.host: "0.0.0.0"